
include: package:flutter_lints/flutter.yaml

linter:
    rules:
        unawaited_futures: true
        omit_local_variable_types: false
        avoid_types_on_closure_parameters: false
        camel_case_types: true
        cancel_subscriptions: true
        comment_references: true
        await_only_futures: true
        exhaustive_cases: true
        avoid_print: true

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
  strong-mode:


#  errors:
#        prefer_single_quotes: ignore

#   exclude:
#     - path/to/excluded/files/**
